// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoM4caFWmWAv_ystxyEiTb09Q19oJBTq4',
    appId: '1:24504040242:web:dc52438281b36895f2752b',
    messagingSenderId: '24504040242',
    projectId: 'flutter-storage-2a7d5',
    authDomain: 'flutter-storage-2a7d5.firebaseapp.com',
    storageBucket: 'flutter-storage-2a7d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlqv1u6BzJv4UvGKBERqoUAfAjyzCZqM',
    appId: '1:24504040242:android:d80d899a31260fc0f2752b',
    messagingSenderId: '24504040242',
    projectId: 'flutter-storage-2a7d5',
    storageBucket: 'flutter-storage-2a7d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUwZMabvsM-SgMao2vfhR6kVseOgsHkdg',
    appId: '1:24504040242:ios:7455d94071b1d89cf2752b',
    messagingSenderId: '24504040242',
    projectId: 'flutter-storage-2a7d5',
    storageBucket: 'flutter-storage-2a7d5.appspot.com',
    iosBundleId: 'com.example.fluuterStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUwZMabvsM-SgMao2vfhR6kVseOgsHkdg',
    appId: '1:24504040242:ios:7455d94071b1d89cf2752b',
    messagingSenderId: '24504040242',
    projectId: 'flutter-storage-2a7d5',
    storageBucket: 'flutter-storage-2a7d5.appspot.com',
    iosBundleId: 'com.example.fluuterStorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoM4caFWmWAv_ystxyEiTb09Q19oJBTq4',
    appId: '1:24504040242:web:6656a33a8f98346bf2752b',
    messagingSenderId: '24504040242',
    projectId: 'flutter-storage-2a7d5',
    authDomain: 'flutter-storage-2a7d5.firebaseapp.com',
    storageBucket: 'flutter-storage-2a7d5.appspot.com',
  );
}
